const WINSTON_API_KEY = process.env.WINSTON_API_KEY || "";
const GEMINI_API_KEY = process.env.GEMINI_API_KEY || "";
const GEMINI_MODEL = process.env.GEMINI_MODEL || "gemini-3.6-flash";

const DETECTOR_TIMEOUT_MS = 15000;

export interface AIDetection {
  score: number;
  label: string;
  confidence: string;
}

export interface DetectorResult {
  detection: AIDetection | null;
  log: string;
}

function normalizeScore(raw: number): number {
  let score = raw;
  if (score > 1) score = score / 100;
  if (score < 0) score = 0;
  if (score > 1) score = 1;
  return score;
}

type PostResult = { data: any } | { status: number } | null;

async function postJson(url: string, body: unknown, apiKey?: string): Promise<PostResult> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), DETECTOR_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        ...(apiKey ? { Authorization: `Bearer ${apiKey}` } : {}),
      },
      body: JSON.stringify(body),
      signal: controller.signal,
    });
    if (!res.ok) return { status: res.status };
    const data = await res.json().catch(() => null);
    if (data === null) return { status: 200 };
    return { data };
  } catch (err) {
    console.error(
      `[aiDetector] ${url} error:`,
      err instanceof Error ? err.message : err
    );
    return { status: 0 };
  } finally {
    clearTimeout(timer);
  }
}

async function callWinston(text: string, log: string[]): Promise<AIDetection | null> {
  if (!WINSTON_API_KEY) {
    log.push("winston: skipped (WINSTON_API_KEY not set)");
    return null;
  }
  const r = await postJson(
    "https://api.gowinston.ai/v2/ai-content-detection",
    { text, language: "en", version: "4.16" },
    WINSTON_API_KEY
  );
  if (!r || !("data" in r)) {
    log.push(`winston: HTTP ${r && "status" in r ? r.status : "error"}`);
    return null;
  }
  const d = r.data;
  let score: number | undefined;
  if (typeof d.ai_probability === "number") score = d.ai_probability;
  else if (typeof d.human_probability === "number") score = 1 - d.human_probability;
  else if (typeof d.ai_score === "number") score = d.ai_score;
  else if (typeof d.score === "number") score = d.score;
  if (score === undefined) {
    log.push("winston: no score in response");
    return null;
  }
  log.push("winston: ok");
  return {
    score: normalizeScore(score),
    label: "ai",
    confidence: typeof d.confidence === "string" ? d.confidence : "medium",
  };
}

async function callGemini(text: string, log: string[]): Promise<AIDetection | null> {
  if (!GEMINI_API_KEY) {
    log.push("gemini: skipped (GEMINI_API_KEY not set)");
    return null;
  }
  const r = await postJson(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent`,
    {
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `You are an AI content detector. Rate the likelihood (0 to 100, 100 = definitely AI-written) that the following text was generated by an AI language model. Reply with only the number. Text: ${text}`,
            },
          ],
        },
      ],
      generationConfig: { maxOutputTokens: 10, temperature: 0 },
    },
    GEMINI_API_KEY
  );
  if (!r || !("data" in r)) {
    log.push(`gemini: HTTP ${r && "status" in r ? r.status : "error"}`);
    return null;
  }
  const raw =
    r.data?.candidates?.[0]?.content?.parts
      ?.map((p: { text?: string }) => p.text ?? "")
      .join("") ?? "";
  const match = raw.match(/\d+/);
  if (!match) {
    log.push("gemini: no numeric score in reply");
    return null;
  }
  log.push("gemini: ok");
  return {
    score: normalizeScore(parseFloat(match[0])),
    label: "ai",
    confidence: "low",
  };
}

// Best-effort chain: Gemini → Winston AI. Gemini runs first because replies
// are only 70–150 chars, which several detectors reject as too short. Never
// throws; returns the first usable score, or null if every detector fails.
// The log explains, step by step, why each detector was skipped or failed.
export async function detectAIContentWithLog(text: string): Promise<DetectorResult> {
  const log: string[] = [];
  if (!WINSTON_API_KEY && !GEMINI_API_KEY) {
    log.push("no detector keys set (WINSTON_API_KEY / GEMINI_API_KEY)");
  }
  const gemini = await callGemini(text, log);
  if (gemini) return { detection: gemini, log: log.join(" | ") };
  const winston = await callWinston(text, log);
  if (winston) return { detection: winston, log: log.join(" | ") };
  return { detection: null, log: log.join(" | ") };
}

export async function detectAIContent(text: string): Promise<AIDetection | null> {
  return (await detectAIContentWithLog(text)).detection;
}
